### ISSUE TITLE
По чьим данным?

### ISSUE THREAD

**Issue by akiyatkin** [ange187/weather#1]
В шаблоне указано, что погода по данным Яндекс, а на самом деле похоже что нет..

**Comment by ange187** [comment]
Я не нашла, где указано что по данным яндекс... ты исправил? или я не вижу?


>Четверг, 26 мая 2016, 23:39 +04:00 от Anton Kiyatkin <notifications@github.com>:
>
>В шаблоне указано, что погода по данным Яндекс, а на самом деле похоже что нет..
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or  view it on GitHub


С уважением,
angi ...
ange187@mail.ru

**Comment by akiyatkin** [comment]
Да это я ошибся... указано было у меня..
